version: '3.8'
services:
  chzzdb:
    image: mysql:latest
    container_name: chzzdb
    environment:
      MYSQL_ROOT_PASSWORD: qal,1
      MYSQL_DATABASE: chzzdb
    ports:
      - "3306:3306"


  chzz-redis:
    container_name: chzz-redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"


