spring:
  jpa:
    hibernate:
      ddl-auto: create


cloud:
  aws:
    credentials:
      access-key: test
      secret-key: test
    region:
      static: test
    s3:
      bucket: test
    cloudfront:
      domain: https://test.cloudfront.net

payment:
  toss:
    client-key: test_ck_P9BRQmyarYleDvqAJl9vVJ07KzLN
    security-key: test_sk_ORzdMaqN3woDka0GDmGN35AkYXQG

logging:
  level:
    org.springframework.security: trace
