spring:
  jpa:
    hibernate:
      ddl-auto: create
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#
  datasource:
    url: jdbc:mysql://chzzdb:3306/chzzdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: qal,1
    driver-class-name: com.mysql.cj.jdbc.Driver


payment:
  toss:
    client-key: test_ck_P9BRQmyarYleDvqAJl9vVJ07KzLN
    security-key: test_sk_ORzdMaqN3woDka0GDmGN35AkYXQG
logging:
  level:
    org.springframework.security: trace

management:
  endpoints:
    web:
      exposure:
        include: health
